### ISSUE TITLE
Step is not defined error when inserting manifest URL in block

### ISSUE THREAD

**Issue by skorasaurus** [mathewjordan/display-iiif-viewer#1]
Hi, 

Thanks for this; I happened to find this and I'm intrigued about implementing this in our workplace (would really save time from downloading images manually and reuploading them into our wordpress instance). 

To reproduce:
1. clone repository as of https://github.com/mathewjordan/yith-iiif-wp/commit/017951268580083ada8d89529ec09dd1395c861e (2021-11-24)
2. activate plugin 
3. create page ,add block, insert this URL https://cplorg.contentdm.oclc.org/iiif/info/p4014coll18/8071/manifest.json 

receive error within the block stating "step is not defined";

**Comment by mathewjordan** [comment]
@skorasaurus Thanks or checking this out! 

I believe the issue here might be a mismatch between the URI and the manifest ID within your manifest.

Your manifest URI noted above is:
https://cplorg.contentdm.oclc.org/iiif/info/p4014coll18/8071/manifest.json 

While the `@id` is:
https://cdm16014.contentdm.oclc.org/iiif/p4014coll18:8071/manifest.json

If you feed the block the ID exactly as noted in the manifest [`https://cdm16014.contentdm.oclc.org/iiif/p4014coll18:8071/manifest.json`](https://cdm16014.contentdm.oclc.org/iiif/p4014coll18:8071/manifest.json), it should work (at least in the editor side of things. And just a note, I'm still working through some issues on the front end but this could be minimally usable as early as next week.

**Comment by mathewjordan** [comment]
@skorasaurus, I recommend bringing down the latest commit (252c9a46e1ce48bb20230b865f8e64d6efab41e0 as of 11/27). The Gutenberg interface will be a bit out of sorts but things are starting to come together. Thanks again for checking this out.

**Comment by skorasaurus** [comment]
thanks, I'll check all this out on monday at work  :)

**Comment by skorasaurus** [comment]
Thanks again for the update; yes, with the latest commit - https://github.com/mathewjordan/yith-iiif-wp/commit/252c9a46e1ce48bb20230b865f8e64d6efab41e0 - I no longer received the step error when using the `id` https://cdm16014.contentdm.oclc.org/iiif/p4014coll18:8071/manifest.json

I look forward to its development.
